const products = [
    {
        id: 1,
        name: "Té Seca Barriga",
        category: "bebidas",
        price: 18.00,
        image: "images/products/Té-seca-barriga.webp",
        shortDescription: "Té natural para ayudar a reducir el abdomen.",
        fullDescription: "El té seca barriga ayuda a eliminar líquidos y reducir el abdomen de forma natural.",
        usage: "Tomar una taza al día.",
        benefits: ["Reduce abdomen", "Elimina líquidos", "Natural"],
        warnings: "No recomendado para embarazadas.",
        features: ["Natural", "Bebida", "Reductor"],
        ingredients: []
    },
    {
        id: 2,
        name: "Vitaslim",
        category: "suplementos",
        price: 35.00,
        image: "images/products/Vitaslim.webp",
        shortDescription: "Suplemento vitamínico para apoyar la dieta.",
        fullDescription: "Vitaslim aporta vitaminas y minerales esenciales para el proceso de adelgazamiento.",
        usage: "1 cápsula después del desayuno",
        benefits: ["Aporta vitaminas", "Apoya la dieta", "Mejora energía"],
        warnings: "No exceder la dosis recomendada.",
        features: ["Vitaminas", "Minerales", "Energía"],
        ingredients: []
    },
    {
        id: 3,
        name: "Tereré Detox",
        category: "bebidas",
        price: 20.00,
        image: "images/products/Terere-detox.webp",
        shortDescription: "Tereré con efecto detox.",
        fullDescription: "Ayuda a desintoxicar el organismo y refrescar.",
        usage: "Tomar una vez al día.",
        benefits: ["Desintoxica", "Refresca", "Natural"],
        warnings: "No exceder la dosis recomendada.",
        features: ["Detox", "Bebida", "Natural"],
        ingredients: []
    },
    {
        id: 5,
        name: "Gel Dokmos",
        category: "topicos",
        price: 25.00,
        image: "images/products/Gel-Dokmos.webp",
        shortDescription: "Gel reductor para uso tópico.",
        fullDescription: "Gel Dokmos ayuda a reducir medidas y reafirmar la piel en zonas específicas.",
        usage: "Aplicar sobre la zona deseada diariamente.",
        benefits: ["Reduce medidas", "Reafirma la piel", "Fácil aplicación"],
        warnings: "No aplicar sobre heridas abiertas.",
        features: ["Reductor", "Tópico", "Fácil uso"],
        ingredients: []
    },
    {
        id: 12,
        name: "Combo Extra Forte Detox",
        category: "combos",
        price: 110.00,
        image: "images/products/combo-extraforte-detox.webp",
        shortDescription: "Combo detox extra fuerte.",
        fullDescription: "Desintoxica y potencia la pérdida de peso con fórmula extra fuerte.",
        usage: "Consultar indicaciones de cada producto.",
        benefits: ["Desintoxica", "Extra fuerte", "Resultados rápidos"],
        warnings: "Consultar con el vendedor antes de combinar productos.",
        features: ["Combo", "Detox", "Extra fuerte"],
        ingredients: []
    },
    {
        id: 13,
    name: "Combo Extra Forte",
        category: "combos",
        price: 100.00,
        image: "images/products/Combo-fat-fit-30-15.webp",
        shortDescription: "Combo Fat Fit para resultados completos.",
        fullDescription: "Incluye Fat Fit en dos presentaciones para mayor duración y resultados.",
        usage: "Consultar indicaciones de cada producto.",
        benefits: ["Resultados completos", "Mayor duración"],
        warnings: "Consultar con el vendedor antes de combinar productos.",
        features: ["Combo", "Fat Fit", "Resultados"],
        ingredients: []
    },
    {
        id: 14,
    name: "Combo Principiante",
        category: "combos",
        price: 105.00,
        image: "images/products/combo-fat-fit-black-15-30.webp",
        shortDescription: "Combo Fat Fit Black para resultados intensos.",
        fullDescription: "Incluye Fat Fit Black en dos presentaciones para mayor intensidad.",
        usage: "Consultar indicaciones de cada producto.",
        benefits: ["Resultados intensos", "Mayor intensidad"],
        warnings: "Consultar con el vendedor antes de combinar productos.",
        features: ["Combo", "Fat Fit Black", "Intensidad"],
        ingredients: []
    },
    {
        id: 15,
    name: "Combo Detox",
        category: "combos",
        price: 102.00,
        image: "images/products/Combo-fat-fit-detox-30-15.webp",
        shortDescription: "Combo Fat Fit Detox para desintoxicar y adelgazar.",
        fullDescription: "Incluye Fat Fit Detox en dos presentaciones para mayor efectividad.",
        usage: "Consultar indicaciones de cada producto.",
        benefits: ["Desintoxica", "Adelgaza", "Mayor efectividad"],
        warnings: "Consultar con el vendedor antes de combinar productos.",
        features: ["Combo", "Fat Fit Detox", "Efectividad"],
        ingredients: []
    },
    {
        id: 16,
        name: "Combo Fat Fit Detox Diet Green",
        category: "combos",
        price: 115.00,
        image: "images/products/combo-fatfit-detox-dietgreen.webp",
        shortDescription: "Combo Fat Fit Detox y Diet Green para resultados máximos.",
        fullDescription: "Combinación de Fat Fit Detox y Diet Green para potenciar resultados.",
        usage: "Consultar indicaciones de cada producto.",
        benefits: ["Resultados máximos", "Combinación potente"],
        warnings: "Consultar con el vendedor antes de combinar productos.",
        features: ["Combo", "Fat Fit Detox", "Diet Green"],
        ingredients: []
    },
    {
        id: 17,
        name: "Combo Fat Fit Black Detox",
        category: "combos",
        price: 112.00,
        image: "images/products/combo-fatfitblack-detox.webp",
        shortDescription: "Combo Fat Fit Black y Detox para resultados intensos.",
        fullDescription: "Combinación de Fat Fit Black y Detox para mayor intensidad y desintoxicación.",
        usage: "Consultar indicaciones de cada producto.",
        benefits: ["Resultados intensos", "Desintoxicación"],
        warnings: "Consultar con el vendedor antes de combinar productos.",
        features: ["Combo", "Fat Fit Black", "Detox"],
        ingredients: []
    },
    {
        id: 18,
        name: "Combo Té Diet Green",
        category: "combos",
        price: 80.00,
        image: "images/products/Combo-té-diet-green.webp",
        shortDescription: "Combo de té y Diet Green para acelerar resultados.",
        fullDescription: "Incluye té y Diet Green para potenciar el efecto adelgazante.",
        usage: "Consultar indicaciones de cada producto.",
        benefits: ["Acelera resultados", "Combinación efectiva"],
        warnings: "Consultar con el vendedor antes de combinar productos.",
        features: ["Combo", "Té", "Diet Green"],
        ingredients: []
    },
    {
        id: 19,
    name: "Combo Té Extra Forte",
        category: "combos",
        price: 85.00,
        image: "images/products/Combo-Té-Fat-fit-black.webp",
        shortDescription: "Combo de té y Fat Fit Black para resultados intensos.",
        fullDescription: "Incluye té y Fat Fit Black para potenciar el efecto adelgazante.",
        usage: "Consultar indicaciones de cada producto.",
        benefits: ["Resultados intensos", "Combinación efectiva"],
        warnings: "Consultar con el vendedor antes de combinar productos.",
        features: ["Combo", "Té", "Fat Fit Black"],
        ingredients: []
    },
    {
        id: 20,
    name: "Diet Green - presentación de 15 cápsulas",
        category: "termogenicos",
        price: 20.00,
        image: "images/products/diet-green-15.webp",
        shortDescription: "Presentación de 15 cápsulas de Diet Green.",
        fullDescription: "Ideal para quienes buscan probar Diet Green en formato pequeño.",
        usage: "1 cápsula después del desayuno",
        benefits: ["Formato pequeño", "Efectivo", "Práctico"],
        warnings: "No exceder la dosis recomendada.",
        features: ["Termogénico", "Diet Green", "15 cápsulas"],
        ingredients: []
    },
    {
        id: 21,
    name: "Diet Green - presentación de 30 cápsulas",
        category: "termogenicos",
        price: 35.00,
        image: "images/products/diet-green-30.webp",
        shortDescription: "Presentación de 30 cápsulas de Diet Green.",
        fullDescription: "Ideal para quienes buscan mayor duración de Diet Green.",
        usage: "1 cápsula después del desayuno",
        benefits: ["Mayor duración", "Efectivo", "Práctico"],
        warnings: "No exceder la dosis recomendada.",
        features: ["Termogénico", "Diet Green", "30 cápsulas"],
        ingredients: []
    },
    {
        id: 24,
        name: "Fat Fit Black Principiante-Presentación de 30 cápsulas",
        category: "termogenicos",
        price: 40.00,
        image: "images/products/fat-fit-b.webp",
        shortDescription: "Fat Fit Black Principiante-Presentación de 30 cápsulas para control de peso.",
        fullDescription: "Ayuda a controlar el peso y mejorar la energía.",
        usage: "1 cápsula después del desayuno",
        benefits: ["Control de peso", "Energía", "Efectivo"],
        warnings: "No exceder la dosis recomendada.",
        features: ["Termogénico", "Fat Fit", "Control de peso"],
        ingredients: []
    },
    {
        id: 25,
        name: "Fat Fit Black Principiante-Presentación de 15 cápsulas",
        category: "termogenicos",
        price: 22.00,
        image: "images/products/Fat-fit-black-15.webp",
        shortDescription: "Fat Fit Black Principiante-Presentación de 15 cápsulas para control de peso.",
        fullDescription: "Ideal para quienes buscan probar Fat Fit Black en formato pequeño.",
        usage: "1 cápsula después del desayuno",
        benefits: ["Formato pequeño", "Efectivo", "Práctico"],
        warnings: "No exceder la dosis recomendada.",
        features: ["Termogénico", "Fat Fit Black", "15 cápsulas"],
        ingredients: []
    },
    {
        id: 26,
        name: "Fat Fit Black Extra Forte - presentación de 15 cápsulas",
        category: "termogenicos",
        price: 23.00,
        image: "images/products/Fat-fit-black-15c.webp",
        shortDescription: "Fat Fit Black Extra Forte - presentación de 15 cápsulas.",
        fullDescription: "Ideal para quienes buscan probar Fat Fit Black en formato especial.",
        usage: "1 cápsula después del desayuno",
        benefits: ["Formato especial", "Efectivo", "Práctico"],
        warnings: "No exceder la dosis recomendada.",
        features: ["Termogénico", "Fat Fit Black", "15 cápsulas"],
        ingredients: []
    },
    {
        id: 27,
        name: "Fat Fit Black Extra Forte - presentación de 30 cápsulas",
        category: "termogenicos",
        price: 45.00,
        image: "images/products/fat-fit-black-extra-forte-30.webp",
        shortDescription: "Fat Fit Black Extra Forte - presentación de 30 cápsulas.",
        fullDescription: "Ideal para quienes buscan mayor potencia en Fat Fit Black.",
        usage: "1 cápsula después del desayuno",
        benefits: ["Mayor potencia", "Efectivo", "Práctico"],
        warnings: "No exceder la dosis recomendada.",
        features: ["Termogénico", "Fat Fit Black", "Extra Forte"],
        ingredients: []
    },
    {
        id: 29,
    name: "Fat Fit Detox - presentación de 15 cápsulas",
        category: "detox",
        price: 19.00,
        image: "images/products/fat-fit-detox-15.webp",
        shortDescription: "Presentación de 15 cápsulas de Fat Fit Detox.",
        fullDescription: "Ideal para quienes buscan probar Fat Fit Detox en formato pequeño.",
        usage: "1 cápsula a las 16 pm",
        benefits: ["Formato pequeño", "Desintoxica", "Práctico"],
        warnings: "No exceder la dosis recomendada.",
        features: ["Detox", "Fat Fit", "15 cápsulas"],
        ingredients: []
    },
    {
        id: 30,
    name: "Fat Fit Detox - presentación de 30 cápsulas",
        category: "detox",
        price: 36.00,
        image: "images/products/Fat-fit-detox-30.webp",
        shortDescription: "Presentación de 30 cápsulas de Fat Fit Detox.",
        fullDescription: "Ideal para quienes buscan mayor duración de Fat Fit Detox.",
        usage: "1 cápsula a las 16 pm",
        benefits: ["Mayor duración", "Desintoxica", "Práctico"],
        warnings: "No exceder la dosis recomendada.",
        features: ["Detox", "Fat Fit", "30 cápsulas"],
        ingredients: []
    }
];