const products = [
    {
        id: 2,
        name: "Diet Green",
        category: "termogenicos",
        price: 32.50,
        effectiveness: "alta",
        image: "images/products/Diet-Green.webp",
        shortDescription: "Menos apetito, grasas y peso - Acelera el efecto de la dieta",
        fullDescription: "DIET GREEN: Menos apetito, grasas y peso, formulado para acelerar y potenciar el efecto de la dieta y del movimiento para adelgazar, bajar más kilos y hacerlo más rápidamente, quemar más durante el deporte o el movimiento cotidiano, notar menos apetito para generar menos calorías. El efecto combinado de garcinia cambogia, té verde, quitasona, spirulina, ácido ascórbico, acetrato de Retinol vitamina A, picolinato de cromo maltodextrina soportan efectos fisiológicos excepcionales y apoyan y potencian tu plan dietético.",
        usage: "1 cápsula después del desayuno",
        benefits: [
            "Reduce el apetito significativamente",
            "Acelera la quema de grasas",
            "Potencia el efecto de la dieta",
            "Aumenta la quema durante el ejercicio",
            "Apoya el plan dietético",
            "Ayuda a bajar más kilos rápidamente"
        ],
        warnings: "Si está tomando alguna medicación recetada, no ingiera este producto sin consultar a su médico. Puede interaccionar con los antiarrítmicos, incluida antibióticos y antiinflamatorios. No debe ser administrado a pacientes ancianos y personas debilitadas sin consultar a su médico."
        ,features: ["Alta Potencia", "Control de Apetito", "Termogénico"]
    },
    {
        id: 3,
        name: "Fat Fit Black",
        category: "termogenicos",
        price: 58.75,
        image: "images/products/Fat-Fit-Black.webp",
        fullDescription: "FAT FIT BLACK es un compuesto destinado a personas con dificultades para adelgazar. Además de inhibir el apetito y ayudar en la reeducación alimentaria, proporciona resistencia y energía para la vida diaria. Reduce los antojos de comida y apoya el control de peso, promoviendo una digestión saludable. Actúa como antioxidante y regula los niveles de glucosa en la sangre. El efecto dura más tiempo de saciedad en el cuerpo para quienes ya se adaptaron a Esbelt Fat Fit, te reactiva.",
        ingredients: ["Garcinia cambogia", "Aloe vera", "Sene", "Psyllium", "Berenjena", "Ginseng"],
        usage: "1 cápsula después del desayuno",
        benefits: [
            "Inhibe el apetito naturalmente",
            "Ayuda en la reeducación alimentaria",
            "Proporciona resistencia y energía",
            "Apoya el control de peso",
            "Promueve una digestión saludable",
            "Actúa como antioxidante",
            "Regula los niveles de glucosa"
        ],
        warnings: "No tomar en ayunas. Consulte a su médico antes de usar. No exceder la dosis recomendada.",
        features: ["Alta Potencia", "Control de Apetito", "Fórmula Black"]
    },
    {
        id: 4,
        name: "Fat Fit Detox",
        category: "detox",
        price: 38.99,
        effectiveness: "media",
        image: "images/products/Fat-fit-detox-30.webp",
        fullDescription: "Fat Fit Detox de Esbelt es una fórmula especialmente diseñada para desintoxicar el organismo mientras apoya el proceso de pérdida de peso, eliminando toxinas y mejorando la digestión.",
        usage: "1 cápsula a las 16 pm",
        benefits: [
            "Desintoxica el organismo",
            "Mejora la digestión",
            "Elimina toxinas acumuladas",
            "Mejora la salud intestinal"
        ],
        warnings: "Beber mucha agua durante el uso. Consulte a su médico si tiene problemas digestivos.",
        features: ["Desintoxicante", "Natural", "Mejora Digestión"]
    },
        // PRODUCTOS AGREGADOS AUTOMÁTICAMENTE
        {
            id: 5,
            name: "Gel Dokmos",
            category: "topicos",
            price: 25.00,
            image: "images/products/Gel-Dokmos.webp",
            shortDescription: "Gel reductor para uso tópico.",
            fullDescription: "Gel Dokmos ayuda a reducir medidas y reafirmar la piel en zonas específicas.",
            usage: "Aplicar sobre la zona deseada diariamente.",
            benefits: ["Reduce medidas", "Reafirma la piel", "Fácil aplicación"],
            warnings: "No aplicar sobre heridas abiertas.",
            features: ["Reductor", "Tópico", "Fácil uso"]
        },
        {
            id: 6,
            name: "Gel Lipo Reductor",
            category: "topicos",
            price: 27.00,
            image: "images/products/Gel-lipo-reductor.webp",
            shortDescription: "Gel para reducción de grasa localizada.",
            fullDescription: "Ayuda a reducir la grasa localizada y mejorar la apariencia de la piel.",
            usage: "Aplicar sobre la zona deseada diariamente.",
            benefits: ["Reduce grasa localizada", "Mejora apariencia de la piel"],
            warnings: "Evitar contacto con ojos.",
            features: ["Reductor", "Tópico", "Fácil uso"]
        },
        {
            id: 7,
            name: "Vitaslim",
            category: "suplementos",
            price: 35.00,
            image: "images/products/Vitaslim.webp",
            shortDescription: "Suplemento vitamínico para apoyar la dieta.",
            fullDescription: "Vitaslim aporta vitaminas y minerales esenciales para el proceso de adelgazamiento.",
            usage: "1 cápsula después del desayuno",
            benefits: ["Aporta vitaminas", "Apoya la dieta", "Mejora energía"],
            warnings: "No exceder la dosis recomendada.",
            features: ["Vitaminas", "Minerales", "Energía"]
        },
        {
            id: 8,
            name: "Té Seca Barriga",
            category: "bebidas",
            price: 18.00,
            image: "images/products/Té-seca-barriga.webp",
            shortDescription: "Té natural para ayudar a reducir el abdomen.",
            fullDescription: "El té seca barriga ayuda a eliminar líquidos y reducir el abdomen de forma natural.",
            usage: "Tomar una taza al día.",
            benefits: ["Reduce abdomen", "Elimina líquidos", "Natural"],
            warnings: "No recomendado para embarazadas.",
            features: ["Natural", "Bebida", "Reductor"]
        },
        {
            id: 9,
            name: "Tereré Detox",
            category: "bebidas",
            price: 20.00,
            image: "images/products/Terere-detox.webp",
            shortDescription: "Tereré con efecto detox.",
            fullDescription: "Ayuda a desintoxicar el organismo y refrescar.",
            usage: "Tomar una vez al día.",
            benefits: ["Desintoxica", "Refresca", "Natural"],
            warnings: "No exceder la dosis recomendada.",
            features: ["Detox", "Bebida", "Natural"]
        }
            ,
            // PRODUCTOS Y COMBOS AGREGADOS AUTOMÁTICAMENTE
            {
                id: 10,
                name: "Combo 1 Esbelt Premium",
                category: "combos",
                price: 120.00,
                image: "images/products/Combo-1-Esbelt-Premium.webp",
                shortDescription: "Combo premium para resultados óptimos.",
                fullDescription: "Incluye productos seleccionados para potenciar la pérdida de peso y bienestar.",
                usage: "Consultar indicaciones de cada producto.",
                benefits: ["Resultados óptimos", "Ahorro", "Combinación ideal"],
                warnings: "Consultar con el vendedor antes de combinar productos.",
                features: ["Combo", "Premium", "Resultados"]
            },
            {
                id: 11,
                name: "Combo Diet Green",
                category: "combos",
                price: 90.00,
                image: "images/products/combo-diet-green.webp",
                shortDescription: "Combo con Diet Green para acelerar resultados.",
                fullDescription: "Ideal para quienes buscan potenciar el efecto de Diet Green.",
                usage: "Consultar indicaciones de cada producto.",
                benefits: ["Acelera resultados", "Combinación efectiva"],
                warnings: "Consultar con el vendedor antes de combinar productos.",
                features: ["Combo", "Diet Green", "Resultados"]
            },
            {
                id: 12,
                name: "Combo Extra Forte Detox",
                category: "combos",
                price: 110.00,
                image: "images/products/combo-extraforte-detox.webp",
                shortDescription: "Combo detox extra fuerte.",
                fullDescription: "Desintoxica y potencia la pérdida de peso con fórmula extra fuerte.",
                usage: "Consultar indicaciones de cada producto.",
                benefits: ["Desintoxica", "Extra fuerte", "Resultados rápidos"],
                warnings: "Consultar con el vendedor antes de combinar productos.",
                features: ["Combo", "Detox", "Extra fuerte"]
            },
            {
                id: 13,
                name: "Combo Fat Fit 30+15",
                category: "combos",
                price: 100.00,
                image: "images/products/Combo-fat-fit-30-15.webp",
                shortDescription: "Combo Fat Fit para resultados completos.",
                fullDescription: "Incluye Fat Fit en dos presentaciones para mayor duración y resultados.",
                usage: "Consultar indicaciones de cada producto.",
                benefits: ["Resultados completos", "Mayor duración"],
                warnings: "Consultar con el vendedor antes de combinar productos.",
                features: ["Combo", "Fat Fit", "Resultados"]
            },
            {
                id: 14,
                name: "Combo Fat Fit Black 15+30",
                category: "combos",
                price: 105.00,
                image: "images/products/combo-fat-fit-black-15-30.webp",
                shortDescription: "Combo Fat Fit Black para resultados intensos.",
                fullDescription: "Incluye Fat Fit Black en dos presentaciones para mayor intensidad.",
                usage: "Consultar indicaciones de cada producto.",
                benefits: ["Resultados intensos", "Mayor intensidad"],
                warnings: "Consultar con el vendedor antes de combinar productos.",
                features: ["Combo", "Fat Fit Black", "Intensidad"]
            },
            {
                id: 15,
                name: "Combo Fat Fit Detox 30+15",
                category: "combos",
                price: 102.00,
                image: "images/products/Combo-fat-fit-detox-30-15.webp",
                shortDescription: "Combo Fat Fit Detox para desintoxicar y adelgazar.",
                fullDescription: "Incluye Fat Fit Detox en dos presentaciones para mayor efectividad.",
                usage: "Consultar indicaciones de cada producto.",
                benefits: ["Desintoxica", "Adelgaza", "Mayor efectividad"],
                warnings: "Consultar con el vendedor antes de combinar productos.",
                features: ["Combo", "Fat Fit Detox", "Efectividad"]
            },
            {
                id: 16,
                name: "Combo Fat Fit Detox Diet Green",
                category: "combos",
                price: 115.00,
                image: "images/products/combo-fatfit-detox-dietgreen.webp",
                shortDescription: "Combo Fat Fit Detox y Diet Green para resultados máximos.",
                fullDescription: "Combinación de Fat Fit Detox y Diet Green para potenciar resultados.",
                usage: "Consultar indicaciones de cada producto.",
                benefits: ["Resultados máximos", "Combinación potente"],
                warnings: "Consultar con el vendedor antes de combinar productos.",
                features: ["Combo", "Fat Fit Detox", "Diet Green"]
            },
            {
                id: 17,
                name: "Combo Fat Fit Black Detox",
                category: "combos",
                price: 112.00,
                image: "images/products/combo-fatfitblack-detox.webp",
                shortDescription: "Combo Fat Fit Black y Detox para resultados intensos.",
                fullDescription: "Combinación de Fat Fit Black y Detox para mayor intensidad y desintoxicación.",
                usage: "Consultar indicaciones de cada producto.",
                benefits: ["Resultados intensos", "Desintoxicación"],
                warnings: "Consultar con el vendedor antes de combinar productos.",
                features: ["Combo", "Fat Fit Black", "Detox"]
            },
            {
                id: 18,
                name: "Combo Té Diet Green",
                category: "combos",
                price: 80.00,
                image: "images/products/Combo-té-diet-green.webp",
                shortDescription: "Combo de té y Diet Green para acelerar resultados.",
                fullDescription: "Incluye té y Diet Green para potenciar el efecto adelgazante.",
                usage: "Consultar indicaciones de cada producto.",
                benefits: ["Acelera resultados", "Combinación efectiva"],
                warnings: "Consultar con el vendedor antes de combinar productos.",
                features: ["Combo", "Té", "Diet Green"]
            },
            {
                id: 19,
                name: "Combo Té Fat Fit Black",
                category: "combos",
                price: 85.00,
                image: "images/products/Combo-Té-Fat-fit-black.webp",
                shortDescription: "Combo de té y Fat Fit Black para resultados intensos.",
                fullDescription: "Incluye té y Fat Fit Black para potenciar el efecto adelgazante.",
                usage: "Consultar indicaciones de cada producto.",
                benefits: ["Resultados intensos", "Combinación efectiva"],
                warnings: "Consultar con el vendedor antes de combinar productos.",
                features: ["Combo", "Té", "Fat Fit Black"]
            },
            {
                id: 20,
                name: "Diet Green 15",
                category: "termogenicos",
                price: 20.00,
                image: "images/products/diet-green-15.webp",
                shortDescription: "Presentación de 15 cápsulas de Diet Green.",
                fullDescription: "Ideal para quienes buscan probar Diet Green en formato pequeño.",
                usage: "1 cápsula después del desayuno",
                benefits: ["Formato pequeño", "Efectivo", "Práctico"],
                warnings: "No exceder la dosis recomendada.",
                features: ["Termogénico", "Diet Green", "15 cápsulas"]
            },
            {
                id: 21,
                name: "Diet Green 30",
                category: "termogenicos",
                price: 35.00,
                image: "images/products/diet-green-30.webp",
                shortDescription: "Presentación de 30 cápsulas de Diet Green.",
                fullDescription: "Ideal para quienes buscan mayor duración de Diet Green.",
                usage: "1 cápsula después del desayuno",
                benefits: ["Mayor duración", "Efectivo", "Práctico"],
                warnings: "No exceder la dosis recomendada.",
                features: ["Termogénico", "Diet Green", "30 cápsulas"]
            },
            {
                id: 22,
                name: "Esbelt Premium 2",
                category: "suplementos",
                price: 60.00,
                image: "images/products/Esbelt-Premium-2.webp",
                shortDescription: "Presentación especial de Esbelt Premium.",
                fullDescription: "Suplemento premium para resultados superiores.",
                usage: "1 cápsula después del desayuno",
                benefits: ["Premium", "Resultados superiores", "Efectivo"],
                warnings: "No exceder la dosis recomendada.",
                features: ["Premium", "Suplemento", "Resultados"]
            },
            {
                id: 23,
                name: "Esbelt Premium",
                category: "suplementos",
                price: 55.00,
                image: "images/products/Esbelt-Premium.webp",
                shortDescription: "Suplemento Esbelt Premium.",
                fullDescription: "Suplemento premium para apoyar la dieta y el bienestar.",
                usage: "1 cápsula después del desayuno",
                benefits: ["Premium", "Apoya la dieta", "Bienestar"],
                warnings: "No exceder la dosis recomendada.",
                features: ["Premium", "Suplemento", "Bienestar"]
            },
            {
                id: 24,
                name: "Fat Fit B",
                category: "termogenicos",
                price: 40.00,
                image: "images/products/fat-fit-b.webp",
                shortDescription: "Fat Fit B para control de peso.",
                fullDescription: "Ayuda a controlar el peso y mejorar la energía.",
                usage: "1 cápsula después del desayuno",
                benefits: ["Control de peso", "Energía", "Efectivo"],
                warnings: "No exceder la dosis recomendada.",
                features: ["Termogénico", "Fat Fit", "Control de peso"]
            },
            {
                id: 25,
                name: "Fat Fit Black 15",
                category: "termogenicos",
                price: 22.00,
                image: "images/products/Fat-fit-black-15.webp",
                shortDescription: "Presentación de 15 cápsulas de Fat Fit Black.",
                fullDescription: "Ideal para quienes buscan probar Fat Fit Black en formato pequeño.",
                usage: "1 cápsula después del desayuno",
                benefits: ["Formato pequeño", "Efectivo", "Práctico"],
                warnings: "No exceder la dosis recomendada.",
                features: ["Termogénico", "Fat Fit Black", "15 cápsulas"]
            },
            {
                id: 26,
                name: "Fat Fit Black 15c",
                category: "termogenicos",
                price: 23.00,
                image: "images/products/Fat-fit-black-15c.webp",
                shortDescription: "Presentación especial de 15 cápsulas de Fat Fit Black.",
                fullDescription: "Ideal para quienes buscan probar Fat Fit Black en formato especial.",
                usage: "1 cápsula después del desayuno",
                benefits: ["Formato especial", "Efectivo", "Práctico"],
                warnings: "No exceder la dosis recomendada.",
                features: ["Termogénico", "Fat Fit Black", "15 cápsulas"]
            },
            {
                id: 27,
                name: "Fat Fit Black Extra Forte 30",
                category: "termogenicos",
                price: 45.00,
                image: "images/products/fat-fit-black-extra-forte-30.webp",
                shortDescription: "Fat Fit Black Extra Forte en presentación de 30 cápsulas.",
                fullDescription: "Ideal para quienes buscan mayor potencia en Fat Fit Black.",
                usage: "1 cápsula después del desayuno",
                benefits: ["Mayor potencia", "Efectivo", "Práctico"],
                warnings: "No exceder la dosis recomendada.",
                features: ["Termogénico", "Fat Fit Black", "Extra Forte"]
            },
            {
                id: 28,
                name: "Fat Fit Black Extra Forte",
                category: "termogenicos",
                price: 48.00,
                image: "images/products/Fat-Fit-Black-Extra-Forte.webp",
                shortDescription: "Fat Fit Black Extra Forte para resultados intensos.",
                fullDescription: "Ideal para quienes buscan resultados intensos y rápidos.",
                usage: "1 cápsula después del desayuno",
                benefits: ["Resultados intensos", "Rápidos", "Efectivo"],
                warnings: "No exceder la dosis recomendada.",
                features: ["Termogénico", "Fat Fit Black", "Extra Forte"]
            },
            {
                id: 29,
                name: "Fat Fit Detox 15",
                category: "detox",
                price: 19.00,
                image: "images/products/fat-fit-detox-15.webp",
                shortDescription: "Presentación de 15 cápsulas de Fat Fit Detox.",
                fullDescription: "Ideal para quienes buscan probar Fat Fit Detox en formato pequeño.",
                usage: "1 cápsula a las 16 pm",
                benefits: ["Formato pequeño", "Desintoxica", "Práctico"],
                warnings: "No exceder la dosis recomendada.",
                features: ["Detox", "Fat Fit", "15 cápsulas"]
            },
            {
                id: 30,
                name: "Fat Fit Detox 30",
                category: "detox",
                price: 36.00,
                image: "images/products/Fat-fit-detox-30.webp",
                shortDescription: "Presentación de 30 cápsulas de Fat Fit Detox.",
                fullDescription: "Ideal para quienes buscan mayor duración de Fat Fit Detox.",
                usage: "1 cápsula a las 16 pm",
                benefits: ["Mayor duración", "Desintoxica", "Práctico"],
                warnings: "No exceder la dosis recomendada.",
                features: ["Detox", "Fat Fit", "30 cápsulas"]
            }
];